cp -a ../linux/drivers/block/deadline-iosched.c drivers/block/
cp -a ../linux/drivers/block/elevator.c drivers/block/
cp -a ../linux/drivers/block/genhd.c drivers/block/
cp -a ../linux/drivers/block/ll_rw_blk.c drivers/block/
cp -a ../linux/fs/proc/proc_misc.c fs/proc/
cp -a ../linux/fs/ioctl.c fs/
cp -a ../linux/fs/bio.c fs/
cp -a ../linux/fs/file_table.c fs/
cp -a ../linux/fs/direct-io.c fs/
#cp -a ../linux/kernel/sysctl.c kernel/
cp -a ../linux/include/linux/ucsb_io.h include/linux/
cp -a ../linux/include/linux/fs.h include/linux/
#cp -a ../linux/include/linux/sysctl.h include/linux/
cp -a ../linux/include/linux/bio.h include/linux/
cp -r ../linux/ucsb-test/* ucsb-test
cp -r ../linux/ucsb-doc/* ucsb-doc
